### ISSUE TITLE
It's dub time! (compilation errors)

### ISSUE THREAD

**Issue by MetalMaxMX** [MrcSnm/HipremeEngine#75]
Hey, just had another error when doing a standard bog dub command on my terminal, here let me paste:

api/source/hip/api/data/commons.d(207,17): Error: alias `mem` cannot alias an expression `this , pop`
api/source/hip/api/data/commons.d(150,21): Error: template instance `hip.view.testscene.TestScene.Preload!().finalImpl!().foreachAsset!(IHipAudioClip, pop)` error instantiating
api/source/hip/api/data/commons.d(237,17):        parent scope from here: `mixin ForeachAssetInClass!(TestScene, loadAsset)`
api/source/hip/api/data/commons.d(237,17): Error: mixin `hip.view.testscene.TestScene.Preload!().impl!().preload.ForeachAssetInClass!(TestScene, loadAsset)` error instantiating
api/source/hip/api/data/commons.d(245,72):        parent scope from here: `mixin impl!()`
source/hip/view/testscene.d(25,5):        parent scope from here: `mixin Preload!()`
Error /usr/bin/dmd failed with exit code 1.

Debian 11, DMD 2.102.2, debug build

**Comment by MrcSnm** [comment]
Hello, would you like to enter in the discord server? There you can get a faster help too

https://discord.gg/9vxu8uXX

**Comment by MrcSnm** [comment]
So, those compilation errors were tested by me a little before that. The problem is that it doesn't support the newer DMD versions. There is a bug which seems like a regression which Rikki tested today.

https://github.com/ldc-developers/ldc/issues/4343

**Comment by MrcSnm** [comment]
Btw ,the last version I'm supporting right now is DMD 2.099 (LDC 1.29)

**Comment by MetalMaxMX** [comment]
> Hello, would you like to enter in the discord server? There you can get a faster help too
> 
> https://discord.gg/9vxu8uXX

I am usually hesitant over joining new Discord servers truth be told. I rather have other people also being able to spot the issues on Github so that they can too know what's going on, however, if I do encounter yet another bug (not this one) or something that could be resolved more quickly, I'll drop in and post my findings 








> So, those compilation errors were tested by me a little before that. The problem is that it doesn't support the newer DMD versions. There is a bug which seems like a regression which Rikki tested today.
> 
> [ldc-developers/ldc#4343](https://github.com/ldc-developers/ldc/issues/4343)



> Btw ,the last version I'm supporting right now is DMD 2.099 (LDC 1.29)

All right, would it be possible to have the 'Supports up to compiler version x.y' in the description field of the project? I imagine it would make it easier to know what one has to work with then

**Comment by MrcSnm** [comment]
https://github.com/MrcSnm/HipremeEngine/blob/master/dub.json#L402

I think I put the requirements wrong, it must be <= instead of >=, gonna fix that real quick

**Comment by MrcSnm** [comment]
Btw no problem, keep posting those kind of issues :)
I think the engine build problems is about to reach stability too which is great

**Comment by MetalMaxMX** [comment]
Sure! I'll keep posting those issues. Also great that is going to reach stability. I managed to do a git pull origin and got it working now, even on an unsupported latest DMD. I'd like to see this issue closed once https://github.com/ldc-developers/ldc/issues/4343 is solved though

**Comment by MrcSnm** [comment]
Can you test up? I have done a fix using rikki's workaround: *Turns out /WHOLEARCHIVE does work when you pass in the D library module name. /WHOLEARCHIVE:hipengine_api.*

I have been testing my engine to work on LDC 1.32.0, so, I guess it should be working by now

**Comment by MetalMaxMX** [comment]
It's working fine on my end since some time too. If anything else does happens, I'll report it as usual
